server:
  port: 8888
  servlet:
    context-path: /web-market-carts
spring:
  application:
    name: cart-service
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      fetchRegistry: false
utils:
  cart:
    prefix: SPRING_WEB_