server:
  port: 8888
  servlet:
    context-path: /web-market-stat

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hometask_8
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
integrations:
  core-service:
    url: http://localhost:5555/core
  cart-service:
    url: http://localhost:5555/cart